[package]
name = "raytrace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.27.0"
winit = "0.25.0"
takeable-option = "0.5.0"

[build-dependencies]
gl_generator = "0.14.0"
